//
//  Shelf.h
//  LibraryBrowser
//
//  Created by Yair Szarf on 12/11/13.
//  Copyright (c) 2013 Yair Szarf. All rights reserved.
//

// This class was generated by Core Data  by using the CReate Managed object Subclass. I added the two required methods.

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

@class Book, Library;

@interface Shelf : NSManagedObject

@property (nonatomic, retain) NSString * number;
@property (nonatomic, retain) Library *atLibrary;
@property (nonatomic, retain) NSOrderedSet *books;
@end

@interface Shelf (CoreDataGeneratedAccessors)

- (void)insertObject:(Book *)value inBooksAtIndex:(NSUInteger)idx;
- (void)removeObjectFromBooksAtIndex:(NSUInteger)idx;
- (void)insertBooks:(NSArray *)value atIndexes:(NSIndexSet *)indexes;
- (void)removeBooksAtIndexes:(NSIndexSet *)indexes;
- (void)replaceObjectInBooksAtIndex:(NSUInteger)idx withObject:(Book *)value;
- (void)replaceBooksAtIndexes:(NSIndexSet *)indexes withBooks:(NSArray *)values;
- (void)addBooksObject:(Book *)value;
- (void)removeBooksObject:(Book *)value;
- (void)addBooks:(NSOrderedSet *)values;
- (void)removeBooks:(NSOrderedSet *)values;
@end
